[2021-08-07 16:38:34,512] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.create_presentation_table_supplier 2021-08-07T16:38:33.952135+00:00 [queued]>
[2021-08-07 16:38:34,547] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.create_presentation_table_supplier 2021-08-07T16:38:33.952135+00:00 [queued]>
[2021-08-07 16:38:34,549] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:38:34,550] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 16:38:34,551] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:38:34,570] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_presentation_table_supplier> on 2021-08-07T16:38:33.952135+00:00
[2021-08-07 16:38:34,578] {standard_task_runner.py:52} INFO - Started process 678 to run task
[2021-08-07 16:38:34,592] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'presentation_pipeline', 'create_presentation_table_supplier', '2021-08-07T16:38:33.952135+00:00', '--job-id', '57', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/presentation_pipeline.py', '--cfg-path', '/tmp/tmpfi8x17dy', '--error-file', '/tmp/tmp9e73qj00']
[2021-08-07 16:38:34,594] {standard_task_runner.py:77} INFO - Job 57: Subtask create_presentation_table_supplier
[2021-08-07 16:38:34,696] {logging_mixin.py:104} INFO - Running <TaskInstance: presentation_pipeline.create_presentation_table_supplier 2021-08-07T16:38:33.952135+00:00 [running]> on host c8552014663a
[2021-08-07 16:38:34,827] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=presentation_pipeline
AIRFLOW_CTX_TASK_ID=create_presentation_table_supplier
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T16:38:33.952135+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-07T16:38:33.952135+00:00
[2021-08-07 16:38:34,830] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS presentation.SUPPLIER (
  `SUPPLIER_KEY` int NOT NULL,
  `SUPPLIER_ACCTBAL` text NOT NULL,
  `NATION_NAME` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `PK_SUPPLIER` PRIMARY KEY (`SUPPLIER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
[2021-08-07 16:38:34,847] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 16:38:34,867] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS presentation.SUPPLIER (
  `SUPPLIER_KEY` int NOT NULL,
  `SUPPLIER_ACCTBAL` text NOT NULL,
  `NATION_NAME` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `PK_SUPPLIER` PRIMARY KEY (`SUPPLIER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;, parameters: None
[2021-08-07 16:38:34,874] {dbapi.py:212} INFO - Rows affected: 0
[2021-08-07 16:38:34,900] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=presentation_pipeline, task_id=create_presentation_table_supplier, execution_date=20210807T163833, start_date=20210807T163834, end_date=20210807T163834
[2021-08-07 16:38:34,969] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-07 16:38:35,007] {local_task_job.py:149} INFO - Task exited with return code 0
