[2021-08-08 11:07:44,935] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.presentation_pipeline_start 2021-08-08T11:07:44.324123+00:00 [queued]>
[2021-08-08 11:07:44,957] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.presentation_pipeline_start 2021-08-08T11:07:44.324123+00:00 [queued]>
[2021-08-08 11:07:44,958] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 11:07:44,959] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-08 11:07:44,959] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 11:07:44,967] {taskinstance.py:1107} INFO - Executing <Task(ExternalTaskSensor): presentation_pipeline_start> on 2021-08-08T11:07:44.324123+00:00
[2021-08-08 11:07:44,976] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'presentation_pipeline', 'presentation_pipeline_start', '2021-08-08T11:07:44.324123+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/presentation_pipeline.py', '--cfg-path', '/tmp/tmp3z7w06bs', '--error-file', '/tmp/tmpwuwmd8vw']
[2021-08-08 11:07:44,972] {standard_task_runner.py:52} INFO - Started process 589 to run task
[2021-08-08 11:07:44,977] {standard_task_runner.py:77} INFO - Job 30: Subtask presentation_pipeline_start
[2021-08-08 11:07:45,021] {logging_mixin.py:104} INFO - Running <TaskInstance: presentation_pipeline.presentation_pipeline_start 2021-08-08T11:07:44.324123+00:00 [running]> on host ce886ce1d63a
[2021-08-08 11:07:45,073] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=presentation_pipeline
AIRFLOW_CTX_TASK_ID=presentation_pipeline_start
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T11:07:44.324123+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-08T11:07:44.324123+00:00
[2021-08-08 11:07:45,074] {external_task.py:152} INFO - Poking for standardized_pipeline.standardized_pipeline_end on 2021-08-08T11:07:44.324123+00:00 ... 
[2021-08-08 11:07:55,080] {local_task_job.py:198} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-08-08 11:07:55,084] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 589
[2021-08-08 11:07:55,085] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-08-08 11:07:55,113] {process_utils.py:66} INFO - Process psutil.Process(pid=589, status='terminated', exitcode=0, started='11:07:44') (589) terminated with exit code 0
