[2021-08-08 08:03:27,128] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:03:27,156] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:03:27,157] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:03:27,158] {taskinstance.py:1088} INFO - Starting attempt 1 of 11
[2021-08-08 08:03:27,158] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:03:27,170] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_customers> on 2021-08-08T07:00:00+00:00
[2021-08-08 08:03:27,175] {standard_task_runner.py:52} INFO - Started process 947 to run task
[2021-08-08 08:03:27,180] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_customers', '2021-08-08T07:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpde8dhtyt', '--error-file', '/tmp/tmp42gxp2uy']
[2021-08-08 08:03:27,183] {standard_task_runner.py:77} INFO - Job 12: Subtask create_standardized_table_customers
[2021-08-08 08:03:27,240] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [running]> on host e453c42896df
[2021-08-08 08:03:27,325] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_customers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T07:00:00+00:00
[2021-08-08 08:03:27,326] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0
[2021-08-08 08:03:27,351] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/hooks/mysql.py", line 164, in get_conn
    getattr(self, self.conn_name_attr)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `dwh_id` isn't defined
[2021-08-08 08:03:27,354] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=standardized_pipeline, task_id=create_standardized_table_customers, execution_date=20210808T070000, start_date=20210808T080327, end_date=20210808T080327
[2021-08-08 08:03:27,404] {local_task_job.py:149} INFO - Task exited with return code 1
[2021-08-08 08:19:21,133] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:19:21,163] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:19:21,164] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:19:21,165] {taskinstance.py:1088} INFO - Starting attempt 1 of 11
[2021-08-08 08:19:21,166] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:19:21,177] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_customers> on 2021-08-08T07:00:00+00:00
[2021-08-08 08:19:21,186] {standard_task_runner.py:52} INFO - Started process 276 to run task
[2021-08-08 08:19:21,191] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_customers', '2021-08-08T07:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmp23w8boww', '--error-file', '/tmp/tmppjo5bm3q']
[2021-08-08 08:19:21,193] {standard_task_runner.py:77} INFO - Job 12: Subtask create_standardized_table_customers
[2021-08-08 08:19:21,280] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [running]> on host 99d60a4279b8
[2021-08-08 08:19:21,367] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_customers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T07:00:00+00:00
[2021-08-08 08:19:21,368] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0
[2021-08-08 08:19:21,383] {base.py:78} INFO - Using connection to: id: dwh_id. Host: deh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 08:19:21,398] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/hooks/mysql.py", line 173, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'deh' (22)")
[2021-08-08 08:19:21,403] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=standardized_pipeline, task_id=create_standardized_table_customers, execution_date=20210808T070000, start_date=20210808T081921, end_date=20210808T081921
[2021-08-08 08:19:21,449] {local_task_job.py:149} INFO - Task exited with return code 1
[2021-08-08 08:31:38,150] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:31:38,191] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:31:38,193] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:31:38,194] {taskinstance.py:1088} INFO - Starting attempt 1 of 11
[2021-08-08 08:31:38,195] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:31:38,221] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_customers> on 2021-08-08T07:00:00+00:00
[2021-08-08 08:31:38,230] {standard_task_runner.py:52} INFO - Started process 237 to run task
[2021-08-08 08:31:38,256] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_customers', '2021-08-08T07:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpglwizgqo', '--error-file', '/tmp/tmpb1lwphlb']
[2021-08-08 08:31:38,261] {standard_task_runner.py:77} INFO - Job 9: Subtask create_standardized_table_customers
[2021-08-08 08:31:38,376] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [running]> on host 5e970160fe16
[2021-08-08 08:31:38,488] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_customers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T07:00:00+00:00
[2021-08-08 08:31:38,489] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0
[2021-08-08 08:31:38,503] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 08:31:38,522] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0, parameters: None
[2021-08-08 08:31:38,554] {dbapi.py:212} INFO - Rows affected: 0
[2021-08-08 08:31:38,573] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=standardized_pipeline, task_id=create_standardized_table_customers, execution_date=20210808T070000, start_date=20210808T083138, end_date=20210808T083138
[2021-08-08 08:31:38,649] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-08 08:31:38,673] {local_task_job.py:149} INFO - Task exited with return code 0
[2021-08-08 08:51:08,877] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:51:08,898] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [queued]>
[2021-08-08 08:51:08,900] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:51:08,901] {taskinstance.py:1088} INFO - Starting attempt 1 of 11
[2021-08-08 08:51:08,901] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 08:51:08,937] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_customers> on 2021-08-08T07:00:00+00:00
[2021-08-08 08:51:08,942] {standard_task_runner.py:52} INFO - Started process 287 to run task
[2021-08-08 08:51:08,957] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_customers', '2021-08-08T07:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmprir3j15n', '--error-file', '/tmp/tmpo1v05_wj']
[2021-08-08 08:51:08,960] {standard_task_runner.py:77} INFO - Job 8: Subtask create_standardized_table_customers
[2021-08-08 08:51:09,053] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_customers 2021-08-08T07:00:00+00:00 [running]> on host 99eefc5c6cd8
[2021-08-08 08:51:09,152] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_customers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T07:00:00+00:00
[2021-08-08 08:51:09,153] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0
[2021-08-08 08:51:09,182] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 08:51:09,198] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.customers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
LIMIT 0, parameters: None
[2021-08-08 08:51:09,222] {dbapi.py:212} INFO - Rows affected: 0
[2021-08-08 08:51:09,239] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=standardized_pipeline, task_id=create_standardized_table_customers, execution_date=20210808T070000, start_date=20210808T085108, end_date=20210808T085109
[2021-08-08 08:51:09,298] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-08 08:51:09,343] {local_task_job.py:149} INFO - Task exited with return code 0
