[2021-08-07 16:37:35,230] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.create_presentation_table_customer 2021-08-07T16:37:34.047037+00:00 [queued]>
[2021-08-07 16:37:35,265] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.create_presentation_table_customer 2021-08-07T16:37:34.047037+00:00 [queued]>
[2021-08-07 16:37:35,267] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:37:35,268] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 16:37:35,269] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:37:35,284] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_presentation_table_customer> on 2021-08-07T16:37:34.047037+00:00
[2021-08-07 16:37:35,298] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'presentation_pipeline', 'create_presentation_table_customer', '2021-08-07T16:37:34.047037+00:00', '--job-id', '47', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/presentation_pipeline.py', '--cfg-path', '/tmp/tmpdfqteskd', '--error-file', '/tmp/tmpg0rsj4_q']
[2021-08-07 16:37:35,292] {standard_task_runner.py:52} INFO - Started process 568 to run task
[2021-08-07 16:37:35,302] {standard_task_runner.py:77} INFO - Job 47: Subtask create_presentation_table_customer
[2021-08-07 16:37:35,382] {logging_mixin.py:104} INFO - Running <TaskInstance: presentation_pipeline.create_presentation_table_customer 2021-08-07T16:37:34.047037+00:00 [running]> on host c8552014663a
[2021-08-07 16:37:35,453] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=presentation_pipeline
AIRFLOW_CTX_TASK_ID=create_presentation_table_customer
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T16:37:34.047037+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-07T16:37:34.047037+00:00
[2021-08-07 16:37:35,455] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS presentation.CUSTOMER (
  `CUSTOMER_KEY` int NOT NULL,
  `NATION_NAME` text NOT NULL,
  `CUSTOMER_ACCTBAL` int NOT NULL,
  `CUSTOMER_MKTSEGMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `PK_CUSTOMER` PRIMARY KEY (`CUSTOMER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
[2021-08-07 16:37:35,467] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 16:37:35,480] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS presentation.CUSTOMER (
  `CUSTOMER_KEY` int NOT NULL,
  `NATION_NAME` text NOT NULL,
  `CUSTOMER_ACCTBAL` int NOT NULL,
  `CUSTOMER_MKTSEGMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `PK_CUSTOMER` PRIMARY KEY (`CUSTOMER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;, parameters: None
[2021-08-07 16:37:35,484] {dbapi.py:212} INFO - Rows affected: 0
[2021-08-07 16:37:35,496] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=presentation_pipeline, task_id=create_presentation_table_customer, execution_date=20210807T163734, start_date=20210807T163735, end_date=20210807T163735
[2021-08-07 16:37:35,545] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-07 16:37:35,562] {local_task_job.py:149} INFO - Task exited with return code 0
