[2021-08-07 15:03:39,705] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.standardized_parts 2021-08-07T14:55:00+00:00 [queued]>
[2021-08-07 15:03:39,721] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.standardized_parts 2021-08-07T14:55:00+00:00 [queued]>
[2021-08-07 15:03:39,722] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 15:03:39,722] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 15:03:39,724] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 15:03:39,772] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): standardized_parts> on 2021-08-07T14:55:00+00:00
[2021-08-07 15:03:39,777] {standard_task_runner.py:52} INFO - Started process 8542 to run task
[2021-08-07 15:03:39,789] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'standardized_parts', '2021-08-07T14:55:00+00:00', '--job-id', '124', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpexxdrtir', '--error-file', '/tmp/tmpqoxw98cn']
[2021-08-07 15:03:39,796] {standard_task_runner.py:77} INFO - Job 124: Subtask standardized_parts
[2021-08-07 15:03:39,910] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.standardized_parts 2021-08-07T14:55:00+00:00 [running]> on host ab70d6dafbc6
[2021-08-07 15:03:40,007] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=standardized_parts
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T14:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-07T14:55:00+00:00
[2021-08-07 15:03:40,008] {mysql.py:70} INFO - Executing: INSERT IGNORE INTO standardized.PART(
	`PART_KEY`,
    `PART_NAME`,
    `PART_MFGR`,
    `PART_BRAND`,
    `PART_TYPE`,
    `PART_SIZE`,
    `PART_CONTAINER`,
    `PART_RETAILPRICE`,
    `PART_COMMENT`,
) 

WITH part_last_5_minutes AS (
	SELECT
        CAST(P_PARTKEY AS SIGNED) AS P_PARTKEY,
        P_NAME,
        P_MFGR,
        P_BRAND,
        P_TYPE,
        CAST(P_SIZE AS SIGNED) AS P_SIZE,
        P_CONTAINER,
        P_RETAILPRICE,
        P_COMMENT
    FROM
        datalake.PART
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	part_last_5_minutes
[2021-08-07 15:03:40,022] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 15:03:40,042] {dbapi.py:204} INFO - Running statement: INSERT IGNORE INTO standardized.PART(
	`PART_KEY`,
    `PART_NAME`,
    `PART_MFGR`,
    `PART_BRAND`,
    `PART_TYPE`,
    `PART_SIZE`,
    `PART_CONTAINER`,
    `PART_RETAILPRICE`,
    `PART_COMMENT`,
) 

WITH part_last_5_minutes AS (
	SELECT
        CAST(P_PARTKEY AS SIGNED) AS P_PARTKEY,
        P_NAME,
        P_MFGR,
        P_BRAND,
        P_TYPE,
        CAST(P_SIZE AS SIGNED) AS P_SIZE,
        P_CONTAINER,
        P_RETAILPRICE,
        P_COMMENT
    FROM
        datalake.PART
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	part_last_5_minutes, parameters: None
[2021-08-07 15:03:40,048] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') \n\nWITH part_last_5_minutes AS (\n\tSELECT\n        CAST(P_PARTKEY AS SIGNED) AS P' at line 11")
[2021-08-07 15:03:40,054] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=standardized_parts, execution_date=20210807T145500, start_date=20210807T150339, end_date=20210807T150340
[2021-08-07 15:03:40,094] {local_task_job.py:149} INFO - Task exited with return code 1
