[2021-08-08 02:15:00,711] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [queued]>
[2021-08-08 02:15:00,758] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [queued]>
[2021-08-08 02:15:00,762] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:15:00,765] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-08 02:15:00,767] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:15:00,787] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_part_suppliers> on 2021-08-08T02:10:00+00:00
[2021-08-08 02:15:00,796] {standard_task_runner.py:52} INFO - Started process 469 to run task
[2021-08-08 02:15:00,808] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_part_suppliers', '2021-08-08T02:10:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpijma6jeq', '--error-file', '/tmp/tmpotcyqx5s']
[2021-08-08 02:15:00,810] {standard_task_runner.py:77} INFO - Job 18: Subtask create_standardized_table_part_suppliers
[2021-08-08 02:15:00,955] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [running]> on host d995c427c378
[2021-08-08 02:15:01,087] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_part_suppliers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T02:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T02:10:00+00:00
[2021-08-08 02:15:01,088] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.part_suppliers AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(PS_PARTKEY AS SIGNED) AS PART_KEY,
        CAST(PS_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        CAST(PS_AVAILQTY AS SIGNED) AS PART_AVAILABILITY_QUANTITY,
        CAST(PS_SUPPLYCOST AS SIGNED) AS PART_SUPPLY_COST, 
        PS_COMMENT AS PART_SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PARTSUPP
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes
[2021-08-08 02:15:01,109] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 02:15:01,131] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.part_suppliers AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(PS_PARTKEY AS SIGNED) AS PART_KEY,
        CAST(PS_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        CAST(PS_AVAILQTY AS SIGNED) AS PART_AVAILABILITY_QUANTITY,
        CAST(PS_SUPPLYCOST AS SIGNED) AS PART_SUPPLY_COST, 
        PS_COMMENT AS PART_SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PARTSUPP
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes, parameters: None
[2021-08-08 02:15:01,139] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1067, "Invalid default value for 'INGESTION_TIMESTAMP'")
[2021-08-08 02:15:01,145] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_part_suppliers, execution_date=20210808T021000, start_date=20210808T021500, end_date=20210808T021501
[2021-08-08 02:15:01,240] {local_task_job.py:149} INFO - Task exited with return code 1
[2021-08-08 02:17:24,611] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [queued]>
[2021-08-08 02:17:24,816] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [queued]>
[2021-08-08 02:17:24,819] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:17:24,821] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-08 02:17:24,823] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-08 02:17:24,881] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_part_suppliers> on 2021-08-08T02:10:00+00:00
[2021-08-08 02:17:24,990] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_part_suppliers', '2021-08-08T02:10:00+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmp7beqtuxh', '--error-file', '/tmp/tmp_uz9ty7y']
[2021-08-08 02:17:24,997] {standard_task_runner.py:77} INFO - Job 20: Subtask create_standardized_table_part_suppliers
[2021-08-08 02:17:24,938] {standard_task_runner.py:52} INFO - Started process 676 to run task
[2021-08-08 02:17:25,518] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_part_suppliers 2021-08-08T02:10:00+00:00 [running]> on host d995c427c378
[2021-08-08 02:17:25,904] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_part_suppliers
AIRFLOW_CTX_EXECUTION_DATE=2021-08-08T02:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-08T02:10:00+00:00
[2021-08-08 02:17:25,914] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.part_suppliers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(PS_PARTKEY AS SIGNED) AS PART_KEY,
        CAST(PS_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        CAST(PS_AVAILQTY AS SIGNED) AS PART_AVAILABILITY_QUANTITY,
        CAST(PS_SUPPLYCOST AS SIGNED) AS PART_SUPPLY_COST, 
        PS_COMMENT AS PART_SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PARTSUPP
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes
[2021-08-08 02:17:25,968] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-08 02:17:26,092] {dbapi.py:204} INFO - Running statement: CREATE TABLE IF NOT EXISTS standardized.part_suppliers (INGESTION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) AS
WITH data_last_5_minutes AS (
	SELECT
        DISTINCT
        CAST(PS_PARTKEY AS SIGNED) AS PART_KEY,
        CAST(PS_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        CAST(PS_AVAILQTY AS SIGNED) AS PART_AVAILABILITY_QUANTITY,
        CAST(PS_SUPPLYCOST AS SIGNED) AS PART_SUPPLY_COST, 
        PS_COMMENT AS PART_SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PARTSUPP
    WHERE 
        INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
)

SELECT 
	* 
FROM 
	data_last_5_minutes, parameters: None
[2021-08-08 02:17:26,248] {dbapi.py:212} INFO - Rows affected: 0
[2021-08-08 02:17:26,370] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=standardized_pipeline, task_id=create_standardized_table_part_suppliers, execution_date=20210808T021000, start_date=20210808T021724, end_date=20210808T021726
[2021-08-08 02:17:26,670] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-08 02:17:26,778] {local_task_job.py:149} INFO - Task exited with return code 0
